### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by bseber** [focus-shift/landingpage#1]
![canvas](https://user-images.githubusercontent.com/1732200/97088859-11f03f00-1634-11eb-9b1f-0bf2c5d389b3.png)
![001](https://user-images.githubusercontent.com/1732200/97088860-14529900-1634-11eb-9d0e-54908573a3d7.png)
![002](https://user-images.githubusercontent.com/1732200/97088861-1583c600-1634-11eb-928f-6c174a527bb1.png)
![003](https://user-images.githubusercontent.com/1732200/97088862-161c5c80-1634-11eb-9dab-987e59ea39bd.png)

**Comment by derTobsch** [comment]
Wir sind live.
